// <auto-generated />
using System;
using CovidCases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidCases.Migrations
{
    [DbContext(typeof(CovidDataContext))]
    partial class CovidDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CovidCases.Models.CovidData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("hosp_patients")
                        .HasColumnType("int");

                    b.Property<string>("iso_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("new_cases")
                        .HasColumnType("int");

                    b.Property<int>("new_deaths")
                        .HasColumnType("int");

                    b.Property<int>("new_vaccinations")
                        .HasColumnType("int");

                    b.Property<int>("people_fully_vaccinated")
                        .HasColumnType("int");

                    b.Property<int>("people_fully_vaccinated_per_hundred")
                        .HasColumnType("int");

                    b.Property<int>("people_vaccinated")
                        .HasColumnType("int");

                    b.Property<int>("positive_rate")
                        .HasColumnType("int");

                    b.Property<int>("total_cases")
                        .HasColumnType("int");

                    b.Property<int>("total_deaths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CovidData");
                });
#pragma warning restore 612, 618
        }
    }
}
